{
 "title": "Dashboard - Apache Web Server",
 "description": "Apache Web Server - Prometheus Dashboard Metrics server-status HTTPD ",
 "tags": [
  "Apache",
  "Web Server"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "host", "label": "host", "query": { "query": "label_values(instance)" } },
   {
    "name": "port",
    "query": {
     "query": "label_values(apache_info,instance)"
    }
   },
   { "name": "job", "query": { "query": "label_values(job)" } },
   {
    "name": "port_node",
    "query": {
     "query": "label_values(node_uname_info{job=\"$job\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Operating System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_time_seconds{instance=\"$host:$port_node\",job=\"$job\"} - node_boot_time_seconds{instance=\"$host:$port_node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "HOSTNAME",
   "type": "stat",
   "description": "HostName",
   "gridPos": { "h": 4, "w": 6, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_uname_info{job=\"$job\", instance=\"$host:$port_node\"}",
     "legendFormat": "{{nodename}}"
    }
   ]
  },
  {
   "title": "CPU Cores",
   "type": "stat",
   "description": "Total number of CPU cores",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=\"$host:$port_node\",job=\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "RAM Used",
   "type": "stat",
   "description": "Non available RAM memory",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"$host:$port_node\",job=\"$job\"} * 100) / node_memory_MemTotal_bytes{instance=\"$host:$port_node\",job=\"$job\"})"
    }
   ]
  },
  {
   "title": "CPU Busy",
   "type": "stat",
   "description": "Busy state of all CPU cores together",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=\"$host:$port_node\",job=\"$job\"}) by (cpu))) - avg(sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=\"$host:$port_node\",job=\"$job\"}[$__rate_interval])))) * 100) / count(count(node_cpu_seconds_total{instance=\"$host:$port_node\",job=\"$job\"}) by (cpu))"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=~\"$job\", instance=~\"$host:$port_node\"}"
    }
   ]
  },
  {
   "title": "OS",
   "type": "stat",
   "description": "System OS",
   "gridPos": { "h": 4, "w": 6, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_os_info{job=~\"$job\",instance=~\"$host:$port_node\"}",
     "legendFormat": "{{name}} - {{version}}"
    }
   ]
  },
  {
   "title": "RAM Total",
   "type": "stat",
   "description": "Total RAM",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$host:$port_node\",job=\"$job\"}"
    }
   ]
  },
  {
   "title": "Root FS Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((node_filesystem_avail_bytes{instance=\"$host:$port_node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"} * 100) / node_filesystem_size_bytes{instance=\"$host:$port_node\",job=\"$job\",mountpoint=\"/\",fstype!=\"rootfs\"})"
    }
   ]
  },
  {
   "title": "SWAP Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "((node_memory_SwapTotal_bytes{instance=\"$host:$port_node\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=\"$host:$port_node\",job=\"$job\"}) / (node_memory_SwapTotal_bytes{instance=\"$host:$port_node\",job=\"$job\"} )) * 100"
    }
   ]
  },
  {
   "title": "1m avg",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load1{instance=\"$host:$port_node\", job=\"$job\"}) / count(count(node_cpu_seconds_total{instance=\"$host:$port_node\", job=\"$job\"}) by (cpu)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5m avg",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load5{instance=\"$host:$port_node\",job=\"$job\"}) / count(count(node_cpu_seconds_total{instance=\"$host:$port_node\",job=\"$job\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "15m avg",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(node_load15{instance=\"$host:$port_node\",job=\"$job\"}) /  count(count(node_cpu_seconds_total{instance=\"$host:$port_node\",job=\"$job\"}) by (cpu)) * 100"
    }
   ]
  },
  {
   "title": "Apache Web Server",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Time during which the server was running",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apache_uptime_seconds_total{instance=~\"$host:$port\"}"
    }
   ]
  },
  {
   "title": "Apache Up / Down",
   "type": "timeseries",
   "description": "Indicates whether the Apache server can be reached or not",
   "gridPos": { "h": 4, "w": 20, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(apache_up{instance=~\"$host:$port\"} == 1)",
     "legendFormat": "Apache Up"
    },
    {
     "expr": "scalar(count(apache_up{instance=~\"$host:$port\"} == 0))",
     "legendFormat": "Apache Down"
    }
   ]
  },
  {
   "title": "Apache Version",
   "type": "stat",
   "description": "The Apache server version",
   "gridPos": { "h": 4, "w": 15, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apache_info{instance=~\"$host:$port\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Apache Load (1min avg)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 5, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(apache_load{instance=\"$host:$port\",interval=\"1min\"})"
    }
   ]
  },
  {
   "title": "Apache Load (5min avg)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(apache_load{instance=\"$host:$port\",interval=\"5min\"})"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "description": "Sumatoria del índice de duración total / Sumatoria del índice de accesos total en 1min",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(apache_duration_ms_total{instance=~\"$host:$port\"}[1m])) / sum(rate(apache_accesses_total{instance=~\"$host:$port\"}[1m]))",
     "legendFormat": "Time"
    }
   ]
  },
  {
   "title": "Apache Server Load",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "apache_load{instance=~\"$host:$port\",job=\"$job\"}",
     "legendFormat": "{{interval}}"
    }
   ]
  },
  {
   "title": "Total Duration Requests ",
   "type": "timeseries",
   "description": "The total duration of all registered requests en ms",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(apache_duration_ms_total{instance=~\"$host:$port\"}[$__rate_interval])",
     "legendFormat": "Time"
    }
   ]
  },
  {
   "title": "Response Size",
   "type": "timeseries",
   "description": "Sumatoria del índice de total de kB enviados  / Sumatoria del índice de accesos total en 5 min",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "sum(rate(apache_sent_kilobytes_total{instance=~\"$host:$port\"}[5m])) / sum(rate(apache_accesses_total{instance=~\"$host:$port\"}[5m]))",
     "legendFormat": "Size"
    }
   ]
  },
  {
   "title": "Current Total kbytes Sent",
   "type": "timeseries",
   "description": "The latest value of total kbytes sent",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "rate(apache_sent_kilobytes_total{instance=~\"$host:$port\"}[$__rate_interval])",
     "legendFormat": "Kilobytes Sent"
    }
   ]
  },
  {
   "title": "Total Accesses",
   "type": "timeseries",
   "description": "Total access count since the server was started",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(apache_accesses_total{instance=~\"$host:$port\"}[$__rate_interval])",
     "legendFormat": "Request"
    }
   ]
  },
  {
   "title": "Apache CPU Time",
   "type": "timeseries",
   "description": "Total duration of all registered requests in ms",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rate(apache_cpu_time_ms_total{instance=~\"$host:$port\"}[$__rate_interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Apache CPU Load",
   "type": "timeseries",
   "description": "The current percentage CPU used by each worker and in total by all workers combined (*)",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (instance) (apache_cpuload{instance=~\"$host:$port\", job=\"$job\"})",
     "legendFormat": "Load"
    }
   ]
  },
  {
   "title": "Apache ScoreBoard Status",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (state)(apache_scoreboard{instance=~\"$host:$port\"})",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "Apache Connection Status",
   "type": "timeseries",
   "description": "Apache connection statuses",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(apache_accesses_total{instance=~\"$host:$port\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apache Worker Status",
   "type": "timeseries",
   "description": "The number of workers serving requests",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "apache_workers{instance=~\"$host:$port\"}",
     "legendFormat": "{{ state }}"
    }
   ]
  },
  {
   "title": "% Workers Busy",
   "type": "timeseries",
   "description": "The number of workers serving requests",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum by (instance)(apache_workers{instance=~\"$host:$port\",state='busy'}) / sum by (instance)(apache_workers{instance=~\"$host:$port\"})",
     "legendFormat": "$host"
    }
   ]
  },
  {
   "title": "Rate Current Total Apache Accesses (5m)",
   "type": "timeseries",
   "description": "Current total apache accesses (*)",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(apache_accesses_total{instance=~\"$host:$port\"}[5m])",
     "legendFormat": "Accesses"
    }
   ]
  },
  {
   "title": "Rate Current Total kbytes Sent - Traffic",
   "type": "timeseries",
   "description": "Sumatoria del índice del total de kB enviados en 5 min",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "sum (rate(apache_sent_kilobytes_total{instance=~\"$host:$port\"}[$__rate_interval]))",
     "legendFormat": "Kilobytes Sent"
    }
   ]
  },
  {
   "title": "Apache Process Count",
   "type": "timeseries",
   "description": "Apache process count",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "apache_workers{instance=~\"$host:$port\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Apache Restart Generation",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "apache_generation{instance=~\"$host:$port\"}",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}